name: Deploy edge functions to Supabase
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase functions deploy lemonsqueezy_webhook  --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
      - run: supabase functions deploy lemonsqueezy_webhook  --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
      - run: supabase functions deploy contact_us            --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}